### ISSUE TITLE
No plot from gen_power_spectrum when nlv = 0

### ISSUE THREAD

**Issue by ArcadeShrimp** [voytekresearch/fooof#111]
Calling `fm.plot()` on a fooof model from `gen_power_spectrum` where `nlv = 0` yields no plot.

**Code Snippet**
`from fooof import FOOOF, FOOOFGroup`
`from fooof.synth import *`

`fs, ps = gen_power_spectrum([1,50], [0,1], [10,.33,.75], nlv=0)`
`fm = FOOOF()`
`fm.add_data(fs, ps)`
`fm.plot()`

**Actual Output**
![fooof_nlv_0](https://user-images.githubusercontent.com/14008089/47882706-a201a200-dde7-11e8-9b89-8bb6d5f47cc6.PNG)

**Expected Output**
![fooof_nlv_0_correct](https://user-images.githubusercontent.com/14008089/47882768-ccebf600-dde7-11e8-85ed-959a52d5f94f.PNG)

**Comment by TomDonoghue** [comment]
This is a very well organized / presented issue: thank you, this makes it much easier to look into and fix. 

This turns out to be a sorta silly bug. The plotting function check if there is data available to plot, checking the variables with 'np.all', which checks all values evaluate as True. A zero causes this to fail, and so nothing gets plotted. This turns out to be an edge case (rare), because it's quite rare to end up with an exact zero in a power spectrum, but it does happen with noiseless synthetic spectra. 

Fix: I changed the data plotting to check the arrays with 'np.any', instead of 'np.all', so it won't fail with zeros. This is pushed to master. 

 @ArcadeShrimp : if you pull and 'pip install .' from master, you should be able to check that this is now fixed. If you don't mind, plot a few things, and sanity check that nothing weird happens with this change. If everything looks good, we can close this issue.

**Comment by ArcadeShrimp** [comment]
It works!
