### ISSUE TITLE
detail peak_params in FOOOFResult

### ISSUE THREAD

**Issue by srcole** [voytekresearch/fooof#66]
Currently, the FOOOFResult object has a peak_params field that has one row per peak and 3 columns per peak. These columns refer to center freq, amp, and bw. However, this is not evident from the object itself or docstrings. 

For example,
```
FOOOFResult(background_params=array([-21.57921891,   0.88217696]),
peak_params=array([[  4.79002936,   0.10790063,   1.        ],
       [ 10.77517628,   0.8725322 ,   2.48344685]]),
r_squared=0.9556209115836026, error=0.06597575096746296,
gaussian_params=array([[  4.79002936,   0.10976303,   0.5       ],
       [ 10.77517628,   0.87284017,   1.24172342]]))
```

It would be nice if the user was more explicitly informed of this structure. Like, instead of having peak_params, we could separate that into center_frequencies, amplitudes, and bandwidths.

**Comment by TomDonoghue** [comment]
I've added a docstring to the FOOOFResults object - just need to copy over these docs to 'get_all_data' (and perhaps anywhere else that it would be useful). 

[Re-architecting the internals to store everything in, for example, CF, Amp & BW vectors instead of the current matrices would be a lot more work, and I'm not convinced it's worth it (better for some things, worse for other) as opposed to better documenting the current version. We though we could revisit this.]

**Comment by TomDonoghue** [comment]
Extract documentation and fix ups to 'get_all_data', including string based data extraction adding, as well more coverage in the tutorials. I think this should cover it, for now at least - can be revisited later if anyone has options / suggestions.
