### ISSUE TITLE
ImportError: cannot import name JSONDecodeError

### ISSUE THREAD

**Issue by dvwz** [voytekresearch/fooof#70]
Hi all, long-time watcher, first time issue submitter:

Encountered an error while importing FOOOF:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "fooof/__init__.py", line 5, in <module>
    from .fit import FOOOF
  File "fooof/fit.py", line 42, in <module>
    from fooof.core.io import save_fm, load_json
  File "fooof/core/io.py", line 6, in <module>
    from json import JSONDecodeError
ImportError: cannot import name JSONDecodeError
```
Is there a required version of the json library that I am not using?

Much thanks!

**Comment by TomDonoghue** [comment]
Hey! Thanks for trying it out!

That is a new error to me. Which version of Python are you using? 

Given that error, it would appear that we do have a minimum version required for json, but not having encountered this before, I'm not sure what version that is, and whether we can relax that on our end, or whether you will perhaps need a newer version of Python.

**Comment by dvwz** [comment]
I am using Python 2.7.13. Or was -- I changed my version of Python to 3.6.0 and it just worked. 

I went back to 2.7.13 and found the version of json, which is 2.0.9 in that installation.  And then I went to 3.6.0, and printed the json version, and it's also 2.0.9! I wonder if there's something else going on between Python and this json version.

Anyway, thanks for suggesting to upgrade.

**Comment by TomDonoghue** [comment]
Ahh, okay - yeh, so 'officially' we only support python3, in particular 3.5 & 3.6. 

I'm not too clear on the version numbering for the json module in particular, but in the python3 son docs it does note that the JSONDecodeError is new in 3.5, so that would explain in (available here: https://docs.python.org/3/library/json.html?highlight=json#json.JSONDecodeError). 

I'm somewhat surprised that that is the first error that pops up when trying to run with 2.7, and it is not particularly helpful regarding the underling problem. We should add a more explicit check that will fail informatively when using a too early version of python. 

Now that you have it up and running, please do let us now of any other comments or quirks you find as you test it out!

**Comment by dvwz** [comment]
Absolutely! Thanks Tom
